---
repos:
  - hooks:
      - args:
          - "--safe"
        id: black
        language_version: python3.7
    repo: "https://github.com/ambv/black"
    rev: 18.9b0

  - hooks:
      - additional_dependencies:
          - black==18.9b0
        id: blacken-docs
        language_version: python3.7
    repo: "https://github.com/asottile/blacken-docs"
    rev: v0.3.0

  - hooks:
      - args:
          - "--application-directories"
          - "src:."
        id: seed-isort-config
    repo: "https://github.com/asottile/seed-isort-config"
    rev: v1.2.0

  - hooks:
      - id: isort
    repo: "https://github.com/pre-commit/mirrors-isort"
    rev: v4.3.4

  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - additional_dependencies:
          - "flake8-bugbear == 18.2.0"
        id: flake8
        language_version: python3.7
    repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v2.0.0

  - hooks:
      - id: pyupgrade
    repo: "https://github.com/asottile/pyupgrade"
    rev: v1.8.0

  - hooks:
      - id: rst-backticks
    repo: "https://github.com/pre-commit/pygrep-hooks"
    rev: v1.1.0
